### ISSUE TITLE
指向url错误

### ISSUE THREAD

**Issue by vlssu** [Hehongyuanlove/flarum-auth-qq#14]
![image](https://user-images.githubusercontent.com/43847794/161429301-bae3b6d1-9fd9-4226-81bc-dab3eba9623d.png)
![GIF 2022-4-3 21-24-40](https://user-images.githubusercontent.com/43847794/161430295-51d37d13-8d34-41e7-9872-0a6af30ae7c8.gif)

没有错误日志生成

**Comment by vlssu** [comment]
https://github.com/Hehongyuanlove/flarum-auth-qq/pull/15

**Comment by vlssu** [comment]
@Hehongyuanlove 现在的问题是，用户名的问题，QQ大部分名字都是中文的，而flarum默认是没有的，导致返回值错误了，还有文字是unicode
![image](https://user-images.githubusercontent.com/43847794/161476267-ca3c4a22-f2c6-48c1-80f1-f5fd4cce20de.png)

**Comment by Hehongyuanlove** [comment]
兼容问题
